#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMvcDemo2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbDemo")]
	public partial class dbDemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttCustomer(tCustomer instance);
    partial void UpdatetCustomer(tCustomer instance);
    partial void DeletetCustomer(tCustomer instance);
    #endregion
		
		public dbDemoDataContext() : 
				base(global::prjMvcDemo2.Properties.Settings.Default.dbDemoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tCustomer> tCustomer
		{
			get
			{
				return this.GetTable<tCustomer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomer")]
	public partial class tCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fId;
		
		private string _fName;
		
		private string _fPhone;
		
		private string _fEmail;
		
		private string _fAddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfPhoneChanging(string value);
    partial void OnfPhoneChanged();
    partial void OnfEmailChanging(string value);
    partial void OnfEmailChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    #endregion
		
		public tCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPhone", DbType="NVarChar(50)")]
		public string fPhone
		{
			get
			{
				return this._fPhone;
			}
			set
			{
				if ((this._fPhone != value))
				{
					this.OnfPhoneChanging(value);
					this.SendPropertyChanging();
					this._fPhone = value;
					this.SendPropertyChanged("fPhone");
					this.OnfPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEmail", DbType="NVarChar(50)")]
		public string fEmail
		{
			get
			{
				return this._fEmail;
			}
			set
			{
				if ((this._fEmail != value))
				{
					this.OnfEmailChanging(value);
					this.SendPropertyChanging();
					this._fEmail = value;
					this.SendPropertyChanged("fEmail");
					this.OnfEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(50)")]
		public string fAddress
		{
			get
			{
				return this._fAddress;
			}
			set
			{
				if ((this._fAddress != value))
				{
					this.OnfAddressChanging(value);
					this.SendPropertyChanging();
					this._fAddress = value;
					this.SendPropertyChanged("fAddress");
					this.OnfAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
